name: Hello Action
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Message to print'
        required: true
        default: "gitlab-1.0.0"

jobs:
  build:
    runs-on: selfhosted
    
    steps:
    - name: Say hello
      run: echo "hello"
