name: Hello Action
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Message to print'
        required: true
        default: "gitlab-1.0.0"

jobs:
  pre-pare:
    runs-on: self-hosted
    
    steps:
    - name: check version
      run: echo "${{ github.event.inputs.version }}"
    - name: checkout
      uses: actions/checkout@v3
    - name: docker login
      run: docker login -u nukoolm -p "${{ secrets.DOCKER_PASS }}"

  build:
    runs-on: self-hosted
    needs: pre-pare
    steps:

      - name: build image
        run: docker build -t  nukoolm/sample-app:${{ github.event.inputs.version }}

      - name: push image 
        run: docker push nukoolm/sample-app:${{ github.event.inputs.version }}
      
      - name: clean local repos
        run: docker rm nukoolm/sample-app:${{ github.event.inputs.version }}
